### ISSUE TITLE
Unable to connect to Cassandra instance

### ISSUE THREAD

**Issue by usax** [HadesArchitect/GrafanaCassandraDatasource#119]
Hi, I am unable to use this plugin to connect to Cassandra. Plugin is asking about below things which i dont see on documentation. 1. It is asking to enter certificate path 2. Root certificate path 3. Root CA certificate path. None of these are there on Graphna instance. If i consider these as optional then also plugin is not able to connect to Cassandra instance. Please suggest ?. Thanks Uma

**Comment by HadesArchitect** [comment]
Hi @usax, these fields are indeed optional. To debug it further, please add:

1. Grafana Logs (at the moment when you try to establish connection)
2. Datasource version, Grafana version
3. Settings you specify on the configuration screen
4. Check if cassandra can be reached via CQLSH using the credentials you use in p.3

**Comment by HadesArchitect** [comment]
Closed due to inactivity
