### ISSUE TITLE
could not find executor for data source (linux_arm64 version missing)

### ISSUE THREAD

**Issue by ChandrasekharRajoli** [HadesArchitect/GrafanaCassandraDatasource#120]
Hi,

I'm getting below error when I try to connect to cassandra datasource. Is this plugin works on macOS (apple m1)?

Please find the below logs

```
grafana                | t=2021-12-09T11:26:40+0000 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=hadesarchitect-cassandra-datasource error="fork/exec /var/lib/grafana/plugins/cassandra/data/grafana/plugins/cassandra/cassandra-plugin_linux_arm64: no such file or directory"
could not find executor for data source type: hadesarchitect-cassandra-datasource" remote_addr=172.x.x.x
```

**Comment by HadesArchitect** [comment]
Hi @ChandrasekharRajoli, 

judging by the logs grafana tries to launch `cassandra-plugin_linux_arm64` version which doesn't exist. That must be a simple thing to add (hopefully), I'll investigate it during the weekend.

**Comment by HadesArchitect** [comment]
Hey @ChandrasekharRajoli, please try version 1.0.1 and let me know if it works for you (or not). https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/tag/1.0.1

**Comment by ChandrasekharRajoli** [comment]
Hey @HadesArchitect 

Thank you. I'll try 1.0.1 version and update you.

**Comment by Nasrem** [comment]
Hi @HadesArchitect , 

Works for me.

Thank you. 👍🏼

**Comment by HadesArchitect** [comment]
Yeah! Thanks for the feedback! I gonna close this ticket and initiate publication of this version at the grafana plugins repo. Just one question, which particular OS version and hardware do you have? Do you run grafana natively or in docker? 

I'm a bit lost because I expected Apple M1 to use `darwin arm64` architecture, but it was `linux arm64` in this case.

**Comment by Nasrem** [comment]
I install the plugin to Grfana 7.5.5 in a Docker container on a NVIDIA jetson Nano.

NVIDIA Jetson Nano
Ubuntu 18.04.6 LTS

**Comment by HadesArchitect** [comment]
Thanks @Nasrem! Could you please execute `uname -m` and `uname -a` commands in that container and paste the output here? Much appreciated!

**Comment by Nasrem** [comment]
aarch64 
Linux grafana-monitoring-7dbd4c68fc-cbglx 4.9.253-tegra #1 SMP PREEMPT Mon Nov 22 21:39:06 CET 2021 aarch64 Linux

**Comment by HadesArchitect** [comment]
Sweeeet. Thanks @Nasrem, looks like we are good! =)

**Comment by ChandrasekharRajoli** [comment]
Hey @HadesArchitect,

its working for me, thank you. Sorry for the late reply :)

**Comment by HadesArchitect** [comment]
Yay! Thanks Chandrasekhar!
