### ISSUE TITLE
cassandra-plugin_linux_amd64: no such file or directory

### ISSUE THREAD

**Issue by joaocps** [HadesArchitect/GrafanaCassandraDatasource#131]
My cassandra database is hosted on another machine but on the same local network. Is there any reason you can't access it this way?

![cassandra_grafana](https://user-images.githubusercontent.com/23501993/159252933-7e9b47b2-57af-4f7d-8e22-6982b271a91a.PNG)

**Comment by smtkhaitan** [comment]
I am also facing same issue. My cassandra is hosted locally.
<img width="1087" alt="Screenshot 2022-03-22 at 10 15 23 AM" src="https://user-images.githubusercontent.com/14147479/159409931-bb0ab072-bb82-4f20-9964-cfd0c06476cc.png">

**Comment by futuarmo** [comment]
Hello! Which version of plugin you are using?

**Comment by smtkhaitan** [comment]
@futuarmo Its **hadesarchitect-cassandra-datasource version: 1.0.0**

**Comment by futuarmo** [comment]
@smtkhaitan our 1.x versions supports only Grafana versions < 8. To use plugin with Grafana 8 and higher please use v2.0. It doesn't published in Grafana Plugins List yet, but now you can download it here and install manually: here is the link:
https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/tag/2.0.0 
Uncompress a file into the Grafana plugins directory (grafana/plugins).

Please, give some feedback when you'll try it

**Comment by futuarmo** [comment]
@joaocps please, tell which version of plugin and Grafana you are using

**Comment by joaocps** [comment]
@futuarmo I'm using the version 8.4.4. I installed the plugin directly from the grafana plugins list, so that must be the problem. I will install manually and then give feedback right back to you. 

Regards!

**Comment by joaocps** [comment]
I downloaded the last release from [](https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/tag/2.0.0), unzip and move the folder to /var/lib/grafana/plugins. Restart the grafana.server service but find out another error:

![image](https://user-images.githubusercontent.com/23501993/159475135-242acd4e-63bf-4c52-ac68-63a305076185.png)

**Comment by HadesArchitect** [comment]
So far I can't reproduce it. 

The path you are having looks wrong to me. You have `/var/lib/grafana/plugins/cassandra-plugin/hadesarchitect-cassandra-datasource/cassandra-plugin_linux_amd64`, the `cassandra-plugin` part seems weird.  Could you please put the folder `hadesarchitect-cassandra-datasource` directly in the `/var/lib/grafana/plugins` ?

**Comment by HadesArchitect** [comment]
Hmmm it's weird. Could you please execute `ls -la /var/lib/grafana/plugins/hadesarchitect-cassandra-datasource` command and paste the results here? Also, if that's possible, I'd schedule a zoom call to debug it further. I can't reproduce it so we may need to debug it together.

**Comment by joaocps** [comment]
@HadesArchitect 
Let me see the best time to schedule this, this week will not be easy for me. Anyway, here's the requested result:
![image](https://user-images.githubusercontent.com/23501993/160857600-63d6f74f-b7d4-4e7d-bc26-5134bc12359d.png)

**Comment by HadesArchitect** [comment]
May relate to our issue: https://forum.golangbridge.org/t/fork-exec-no-such-file-or-directory-ld-preload/23824

**Comment by bygui86** [comment]
@HadesArchitect when do you plan to release v2.0.0 also in the Grafana Plugins Catalog?
Currently is 1.1.4 and it does not support Grafana v8.
Thanks :)

**Comment by HadesArchitect** [comment]
@bygui86 It's already released but currently not published, due to the Grafana's review process. I suggest using [2.0.0](https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/tag/2.0.0)(requires manual installation)

**Comment by HadesArchitect** [comment]
@andrew-landsverk-win @joaocps Could you guys please try to replace the original file with a this one?

[cassandra-plugin_linux_amd64.zip](https://github.com/HadesArchitect/GrafanaCassandraDatasource/files/8445244/cassandra-plugin_linux_amd64.zip)

**Comment by HadesArchitect** [comment]
Mark for myself: https://stackoverflow.com/a/58185179/2214896

**Comment by rbailey90** [comment]
Any progress on this? I'm running into the same issue, Grafana 8.3.3, Plugin version 2.0.0, CentOS 7.

**Comment by PaulB2Code** [comment]
Same Error on our side :
 msg="Could not start plugin" pluginId=hadesarchitect-cassandra-datasource err="fork/exec /var/lib/grafana/plugins/hadesarchitect-cassandra-datasource/cassandra-plugin_linux_amd64: no such file or directory"
 
 Ubuntu 18.04 => Grafana 8.5.0

**Comment by PaulB2Code** [comment]
Dear  @HadesArchitect ,

You solution with the new files work. 
I have to unsigned the plugin in order to test. 

Thank you

**Comment by Snikz18** [comment]
> Dear @HadesArchitect ,
> 
> You solution with the new files work. I have to unsigned the plugin in order to test.
> 
> Thank you

Out of curiosity, how do you unsign the plugin first?

**Comment by PaulB2Code** [comment]
> > Dear @HadesArchitect ,
> > You solution with the new files work. I have to unsigned the plugin in order to test.
> > Thank you
> 
> Out of curiosity, how do you unsign the plugin first?
Stop grafana server

export GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=hadesarchitect-cassandra-datasource

allow_loading_unsigned_plugins=hadesarchitect-cassandra-datasource
in /etc/grafana/grafana.ini 

Remove MANIFEST.txt from folder plugin 
mv /var/lib/grafana/plugins/hadesarchitect-cassandra-datasource/MANIFEST.txt .

And relaunch grafana server
Regards

**Comment by HadesArchitect** [comment]
> You solution with the new files work. I have to unsigned the plugin in order to test.

You are awesome, thank you for your contribution!

I'll release the updated version as 2.0.1 in a couple of hours.

**Comment by Snikz18** [comment]
@PaulB2Code It's not working for me, I've added allow_loading_unsigned_plugins=hadesarchitect-cassandra-datasource manually in the grafana ini, but I get a modified signature error, If i remove the manifest.txt from var/lib/grafana/plugins/hadesarchitect-cassandra-datasource/ I get a plugin not found error. Any help? Am I missing something obvious? P.S. I'm trying with the version 2.1
