### ISSUE TITLE
2.1.0 Refactoring

### ISSUE THREAD

**Issue by HadesArchitect** [HadesArchitect/GrafanaCassandraDatasource#136]
Thank you. Great work. Would still like to see some additional changes before we can publish this. Let us know if you don't agree.
 
**Instance management:**
It does works better now, but I still see that potential raise conditions could occur when initializing the session.
 
As I wrote earlier:

* Since you're using the datasource instance management you should initialize and cache a field on the [CassandraDatasource struct](https://github.com/HadesArchitect/GrafanaCassandraDatasource/blob/2.0.0/backend/datasource.go#L19). To me it seems like the clusterconfig should be initialized and cached on CassandraDatasource struct and then you'll use that to create/open a session per request and close it at the end.
 
We have an example, see https://github.com/grafana/grafana-plugin-examples/blob/master/examples/datasource-basic/pkg/main.go#L20, which I think should simplify your code for serving the plugin and handle the Cassandra connections/sessions. 
 
In the example it uses the [NewDataSource](https://github.com/grafana/grafana-plugin-examples/blob/2055e660f11a11f0221289ce4149a9a54564a952/examples/datasource-basic/pkg/plugin/datasource.go#L33-L43) for instantiating a new datasource instance - this is called each time a datasource in created/updated in Grafana and locking/concurrency guarantees that it only executes exactly once for every datasource created/updated in Grafana . This is the recommended location for instantiating clients and such, e.g. your clusterconfig. 
 
**Logging:**

* For example [this line](https://github.com/HadesArchitect/GrafanaCassandraDatasource/blob/2.1.0/backend/plugin.go#L23) that logs, rather than using logger.Debug(fmt.Sprintf("Created datasource, ID: %d\n", [settings.ID](http://settings.id/))) we recommend to use structured logging, e.g. logger.Debug("Created datasource", "uid", settings.UID)
* Would recommend using lowercase keys when logging, e.g. message instead of Message, to follow Grafana's convention. 
* Inconsistent use of warning/error log levels, e.g. [here](https://github.com/HadesArchitect/GrafanaCassandraDatasource/blob/2.1.0/backend/datasource.go#L132) warning are used and [here](https://github.com/HadesArchitect/GrafanaCassandraDatasource/blob/4cae50876231e6d60d1bdefa5bc43bd4488b6bc0/backend/datasource.go#L304) error are used. Can you please use error level everywhere when logging an error? 
* Please use debug level [here](https://github.com/HadesArchitect/GrafanaCassandraDatasource/blob/2.1.0/backend/datasource.go#L79)
 
Kind regards,
The Grafana Team

**Comment by futuarmo** [comment]
Fixed in #138
