### ISSUE TITLE
No toggle text edit mode

### ISSUE THREAD

**Issue by rgracia-tech** [HadesArchitect/GrafanaCassandraDatasource#141]
Plugin version 2.1.1 installed in Grafana v8.3.3 without issues
Adding a query, no toggle text edit mode button appears, it is not possible to enable query editor. 
Im not sure if it depends on the plugin or i did something wrong.

Thanks and regards,
Ruben Gracia

**Comment by HadesArchitect** [comment]
Hi Ruben, could you please provide a screenshot of a query configurator? I cannot reproduce it, all looks good to me.

**Comment by HadesArchitect** [comment]
Closed due to inactivity, feel free to reopen if it's still an issue.

**Comment by rgracia-tech** [comment]
Hello Aleks,
Thanks for your anwswer and sorry for the delay. This is the screenshot:
![Screenshot from 2022-10-18 15-42-34](https://user-images.githubusercontent.com/57218815/196447770-ebe2fd38-b5d2-42c5-b09d-67d0c5cd7cd1.png)
Maybe I forget something, but you can see text edit mode button doesn't appear.

**Comment by HadesArchitect** [comment]
Errrrr, it's really weird, I have never seen something like that. It's the `panel configuration` page, right?

**Comment by rgracia-tech** [comment]
Yes, clicking in "edit" (It is the edit panel) :)
It is happening with Grafana 9.1.7 too
![Screenshot from 2022-10-18 17-21-31](https://user-images.githubusercontent.com/57218815/196473266-169867a3-1efc-41e5-a5bd-d79ae21f3402.png)

**Comment by HadesArchitect** [comment]
Try this one: 
<img width="125" alt="image" src="https://user-images.githubusercontent.com/1742301/196473566-283230f3-a89b-42f7-aca9-49c10845e1ba.png">

**Comment by rgracia-tech** [comment]
How i couldn't see it? I have doubt if it was in version 8.3.3, im not sure. Maybe it was and i did not see it, like in version 9.1.7
Im very sorry for have wasted you time :(
Thanks!
