### ISSUE TITLE
Astra DB / GoCQL incompatibility: "unable to discover protocol version: Password must not be null"

### ISSUE THREAD

**Issue by tnielens** [HadesArchitect/GrafanaCassandraDatasource#143]
I'm getting this error in grafana's log when I try to connect to an astra instance of mine.
```
gocql: unable to create session: unable to discover protocol version: Password must not be null
```
I do fill the password. Grafana shows the password field empty though once I save. I've tried with astra's client secret and a dummy password. Both result in the same error.

I'm running grafana in docker v9.1.5. I've tested incorrect hostname and cert paths. That fails with the expected error messages. 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/11885535/190754934-1459908f-ab61-4a6a-b316-723b2f1438d2.png">

**Comment by HadesArchitect** [comment]
Hi Tim,

thank you for reporting it with all the details. Next few days I'm busy organising a Cassandra event, but right after that, I'll try to reproduce it and see what I can do, Wednesday or Thursday.

**Comment by danielRV7** [comment]
I'm having exactly the same issue. I will wait till HadesArchitect checks it, since the things I tried did not work.

**Comment by HadesArchitect** [comment]
Work in Progress, looks like I'm getting somewhere :)

**Comment by HadesArchitect** [comment]
Fix to be released as `2.2.1` asap

**Comment by danielRV7** [comment]
> 

Perfect, thanks! Any estimated release date?

**Comment by HadesArchitect** [comment]
@danielRV7 It's already released and available for the manual installation (https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/tag/2.2.1)

The new version will become available in grafana plugin repository in few days
