### ISSUE TITLE
GoCQL: Unable to create session

### ISSUE THREAD

**Issue by danielRV7** [HadesArchitect/GrafanaCassandraDatasource#144]
Hey, I'm using the new 2.2.1 release of the plugin, but when I fill the fields and test the connection it throws me the following error:

<img width="969" alt="Captura de Pantalla 2022-09-27 a las 10 54 35" src="https://user-images.githubusercontent.com/27138015/192481577-0d577ca7-2ebd-48e7-9fc9-08db8f55ab12.png">

And the log:

![Captura de Pantalla 2022-09-27 a las 10 55 04](https://user-images.githubusercontent.com/27138015/192481643-a3905f1b-8f67-4eae-8425-49967a59a765.png)

**Comment by HadesArchitect** [comment]
`Connection refused` means that the driver cannot connect to the Cassandra server, could you please try if you can reach that host and port from the Grafana server to the Cassandra server?

**Comment by danielRV7** [comment]
> `Connection refused` means that the driver cannot connect to the Cassandra server, could you please try if you can reach that host and port from the Grafana server to the Cassandra server?

Oh, I'm sorry, you can close the thread. Last night that machine shut down and I did not know until now.

**Comment by HadesArchitect** [comment]
=)It happens, don't worry :)
