### ISSUE TITLE
Logging data contains entire data frame fetched

### ISSUE THREAD

**Issue by UP929312** [HadesArchitect/GrafanaCassandraDatasource#147]
When using this library, there are dozens of logs that are "warn" level, but also include **all** the data that it just fetched, causing the log files to balloon in size very quickly when working with large amounts of data.

Can these warn level logs not include all the data when outputting to the log file?

**Comment by HadesArchitect** [comment]
Hey @UP929312, thank you for the valuable feedback, you are right, it shouldn't be like that. I'll try to release a hotfix asap.

**Comment by UP929312** [comment]
Thank you @HadesArchitect, I look forward to seeing your change

**Comment by UP929312** [comment]
Any updates on a hotfix?

**Comment by UP929312** [comment]
@HadesArchitect It's been 8 days, can I get an update on this?

**Comment by HadesArchitect** [comment]
Hey, it's been a totally crazy week and I'm really low on time. Could you please send me a screenshot or copy-paste the *beginning* of the log message that bothers you? I can make a quick fix but don't have time to investigate properly where it happens.

**Comment by HadesArchitect** [comment]
It will help me to identify the incorrect logger call.

**Comment by UP929312** [comment]
Thank you. I wrote a script to search all your files for "warn" but it returned nothing, even though this error message is warn, but here it is:

`logger=plugin.hadesarchitect-cassandra-datasource t=2022-11-03T15:08:27.35+0000 lvl=warn msg="[timestamp:1667488107134000000 value:10794.4  timestamp:1667488106872000000 value:10794.8  timestamp:1667488106599000000 value:10794  timestamp:1667488106318000000 value:10793.7  timestamp:1667488106058000000 value:10793.2  timestamp:1667488105259000000 value:10793.7  timestamp:1667488104698000000 value:10793.4  timestamp:1667488104408000000 value:10793.3  timestamp:1667488104127000000 value:10793.4  timestamp:1667488103834000000 value:10792.9  timestamp:1667488103543000000 value:10792.7  timestamp:1667488103218000000 value:10793  timestamp:1667488102597000000 value:10792.7  timestamp:1667488102286000000 value:10793  timestamp:1667488101996000000 value:10791.9  timestamp:1667488101683000000 value:10791.7  timestamp:1667488101103000000 value:10792.2  timestamp:1667`

**Comment by unflag** [comment]
@UP929312 Hey, could you please tell me what plugin version causes problem? As far as I can see recent version doesn't use log level 'warn' at all.

**Comment by UP929312** [comment]
@unflag Ah, it's version 2.0.0 or 2.0.1, was this changed/fixed?

**Comment by HadesArchitect** [comment]
Yes it was 😁
