### ISSUE TITLE
Grafana 7.0 Support

### ISSUE THREAD

**Issue by HadesArchitect** [HadesArchitect/GrafanaCassandraDatasource#15]
https://grafana.com/blog/2020/05/18/grafana-v7.0-released-new-plugin-architecture-visualizations-transformations-native-trace-support-and-more/

`Grafana v7.0 released: New plugin architecture`

**Comment by saleh7755** [comment]
M

**Comment by HadesArchitect** [comment]
Works at 7.3.6
