### ISSUE TITLE
Connection fails when using LDAP Authentication

### ISSUE THREAD

**Issue by ValkyrieOps** [HadesArchitect/GrafanaCassandraDatasource#156]
Hello,
I am uanble to add this datasource due to authentication failures.  Our Cassandra cluster relies on the [Instaclustr LDAP Authenticator](https://github.com/instaclustr/cassandra-ldap), but   alternative authenticators appear to be incompatible with this datasource:

```
logger=plugin.hadesarchitect-cassandra-datasource t=2023-04-12T11:28:38.979311903-05:00 level=error msg="Failed to create Cassandra connection" Message="cluster.CreateSession: gocql: unable to create session: unable to discover protocol version: unexpected authenticator \"org.apache.cassandra.auth.LDAPAuthenticator\""
```

The connection fails when using the local admin `cassandra` user as well.  Please let me know if I can provide any additional information,  thanks

**Comment by unflag** [comment]
Hey! It seems that authenticators are explicitly enabled in [gocql driver itself](https://github.com/gocql/gocql/blob/master/conn.go#L27) and it could not be overridden in datasource level. However, it doesn't feel like a complex patch, except that some testing needs to be done before it's submitted.

**Comment by ValkyrieOps** [comment]
Oh cool that's great news.  I'll see about opening up a pull request over there.  Going to close out this issue since this is not handled by the GrafanaCassandraDatasource project itself.  Thanks!

**Comment by HadesArchitect** [comment]
Apparently requires some work on our side too.
