### ISSUE TITLE
[Alerting] Error parsing $__timeFrom and  $__timeTo

### ISSUE THREAD

**Issue by jacobdebruyn** [HadesArchitect/GrafanaCassandraDatasource#158]
Receiving below error when running query via the "Add Rule" alerting menu 

the query uses grafana in-built time variables  "WHERE timestamp >= $__timeFrom and timestamp < $__timeTo" 
the query works fine within the dashboard panels  

"Error
Failed to evaluate queries and expressions: failed to execute query B: p.ExecQuery: query processing: repo.ExecRawQuery: raw query processing: line 1:224 mismatched character '_' expecting '$'"

**Comment by unflag** [comment]
Hi, thank you for report. 
I reproduced this error locally. Seems a bit strange, need to investigate.
Could you tell what version of grafana do you use?

**Comment by jacobdebruyn** [comment]
hey there, 
the error occurred on 9.5.1 as well as 10.0.2

thanks!

**Comment by HadesArchitect** [comment]
@unflag This one goes to `3.0.0`, right?

**Comment by unflag** [comment]
Yes, that's right. Will fix it as soon as possible.
