### ISSUE TITLE
Data Not refreshing with Grafana 7.2

### ISSUE THREAD

**Issue by parabinda** [HadesArchitect/GrafanaCassandraDatasource#22]
Hi,
I installed Grafana - 7.2.1 
And also created - your Cassandra Data Source as a Plugin.

I tried to create a Query for  Panel - providing - Keyspace, Table_name, ID etc.
But data is not getting fetched.

I get below warning in - Grafana log.
Please help
---------------------------------------
t=2020-10-14T14:26:17+0000 lvl=warn msg="Running an unsigned backend plugin" logger=plugins pluginID=hadesarchitect-cassandra-datasource pluginDir=/var/lib/grafana/plugins/dist
t=2020-10-14T14:26:17+0000 lvl=info msg="Registering plugin" logger=plugins name="Apache Cassandra"
t=2020-10-14T14:26:17+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-10-14T14:26:18+0000 lvl=warn msg="Plugin uses a deprecated version of Grafana's backend plugin system which will be removed in a future release. Consider upgrading to a newer plugin version or reach out to the plugin repository/developer and request an upgrade." logger=plugins.backend pluginId=hadesarchitect-cassandra-datasource
----------------------------------
Thank you.
Regards
Arabinda

**Comment by HadesArchitect** [comment]
Hello Arabinda, thank you for the feedback. I will take a closer look next week, but in short, Grafana v7 uses a new plugin system that isn't supported by the plugin yet.

**Comment by HadesArchitect** [comment]
Hi @parabinda We are tested the datasource today with grafana v7.3, it was fully operational. 

Could you please provide more details on how do you try to fetch data?

**Comment by HadesArchitect** [comment]
Closed as inactive
