### ISSUE TITLE
Publish as an official Grafana datasource

### ISSUE THREAD

**Issue by HadesArchitect** [HadesArchitect/GrafanaCassandraDatasource#36]

**Comment by HadesArchitect** [comment]
https://github.com/grafana/grafana-plugin-repository/projects/2#card-54621931

**Comment by bygui86** [comment]
Amazing!!

**Comment by HadesArchitect** [comment]
@bygui86 Yeah I know! Guess it will be included in the next couple of days.

**Comment by HadesArchitect** [comment]
@bygui86 Esattamente! https://grafana.com/grafana/plugins/hadesarchitect-cassandra-datasource/  Sono molto felice!

**Comment by bygui86** [comment]
Benissimo! Complimenti grande lavoro! Funziona molto bene!!
