### ISSUE TITLE
Multiple archs support

### ISSUE THREAD

**Issue by mdvaliyullah** [HadesArchitect/GrafanaCassandraDatasource#51]
unable to add datasource, getting "Metric request error". Please advise

**Comment by futuarmo** [comment]
Hello! Please, post logs from Grafana when you are trying to send request

**Comment by mdvaliyullah** [comment]
```
t=2020-12-10T11:27:10+0530 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 error="Could not find executor for data source type: hadesarchitect-cassandra-datasource" remote_addr=[::1]
t=2020-12-10T11:27:10+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 method=POST path=/api/tsdb/query status=500 remote_addr=[::1] time_ms=6 size=34 referer=http://localhost:3000/datasources/edit/20/
```

**Comment by futuarmo** [comment]
Do you have problems in RawQueryMode too? 
It really looks like your Cassandra Datasource plugin is not loaded. Please, check it in datasources. Also wrong rights of the file may be the reason of problem - try to permit execution right to cassandra-`plugin_linux_amd64` file with chmod +x command

**Comment by HadesArchitect** [comment]
Please add the configuration information: how does your datasource config look like?

**Comment by mdvaliyullah** [comment]
looked into the logs, getting below error in the logs `EROR[12-11|09:30:23] Failed to start plugin                   logger=plugins.backend pluginId=hadesarchitect-cassandra-datasource error="fork/exec /grafana-5.2.0/data/plugins/cassandra-datasource-0.3.2/dist/cassandra-plugin_darwin_amd64: no such file or directory"`

**Comment by HadesArchitect** [comment]
Ok that makes sense. Looks like the plugin isn't installed correctly.

1. How did you install the plugin? Step by step.
2. Which version did you use

**Comment by mdvaliyullah** [comment]
followed the installation steps in the read me file. I installed the latest 0.3.2 version. is the plugin will work only in linux system?

**Comment by HadesArchitect** [comment]
Oh you are right, at this point, we are to support only Linux. Are you on Windows? Which version? 

Imho it shouldn't be a big deal to support windows, we can try to add it.

**Comment by mdvaliyullah** [comment]
can you please add it for windows and IOS latest version

**Comment by HadesArchitect** [comment]
By IOS you mean OSX? 

We definitely have to support windows, shouldn't be too hard. For the OSX, we should check something.

**Comment by HadesArchitect** [comment]
https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/tag/0.3.3 should have osx/win executables. NOT TESTED. Please write here if it will work for you. 

If there are no assets (zip/tar.gz) attached, it means that the build is not done yet. It should be ready in a few minutes.

**Comment by HadesArchitect** [comment]
Ping @mdvaliyullah Any updates? Have you tried it?

**Comment by HadesArchitect** [comment]
Closing as inactive
