### ISSUE TITLE
Test plugin on Windows

### ISSUE THREAD

**Issue by HadesArchitect** [HadesArchitect/GrafanaCassandraDatasource#59]
Currently, the plugin proved to work on Linux and OS X, but not on Windows.

Todo:

1. Install Grafana on Windows
2. Install the plugin
3. Launch Cassandra (can be a VM or a docker installation)
4. Load test data `test_data.cql`
5. Check that the plugin works and shows the data

**Comment by ekvalizer** [comment]
Grafana version: 7.5.1
Plugin version: 0.5.0
Everything works just fine except for one issue: 
From grafana logs: ```t=2021-03-28 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=hadesarchitect-cassandra-datasource error="exec: \"D:\\\\Program Files\\\\GrafanaLabs\\\\grafana\\\\data\\\\plugins\\\\hadesarchitect-cassandra-datasource\\\\cassandra-plugin_windows_amd64.exe\": file does not exist"```
Seems like grafana looking an `.exe` file, renaming `cassandra-plugin_windows_amd64` to `cassandra-plugin_windows_amd64.exe` solves the problem.
![image](https://user-images.githubusercontent.com/12397119/112764162-c269d100-9020-11eb-9395-7f310d117c93.png)

**Comment by HadesArchitect** [comment]
Hey, great job! Thank you so much!

**Comment by HadesArchitect** [comment]
Closed by #98
