### ISSUE TITLE
Development path.. docker

### ISSUE THREAD

**Issue by synedra-datastax** [HadesArchitect/GrafanaCassandraDatasource#69]
Couldn't we provide a solid docker image people could use, instead of all these commands?

**Comment by HadesArchitect** [comment]
These build instructions are for development purposes, they are only for people developing the plugin. Normal user-faced installation doesn't include any build steps but just downloading of the compiled plugin.

What's missing indeed is a simple way to run the grafana with the enabled plugin without build steps for those who want to try but not to develop. I'll create a stand-alone ticket for that. 

Thank you for the feedback!
