### ISSUE TITLE
Failed to start docker-compose 'No container found for cassandra_1'

### ISSUE THREAD

**Issue by synedra-datastax** [HadesArchitect/GrafanaCassandraDatasource#71]
Did I start a cassandra_1 container?  I don't think I started a cassandra_1 container:

khunter-rmbp15:GrafanaCassandraDatasource kirstenhunter$ docker-compose exec cassandra cqlsh -u cassandra -p cassandra -f ./test_data.cql
ERROR: No container found for cassandra_1

The paths through the instructions need to be crystal clear.  Right now there's no clue which things I should or shouldn't do.

khunter-rmbp15:GrafanaCassandraDatasource kirstenhunter$ docker-compose up -d
Starting grafanacassandradatasource_cassandra_1 ... 
Starting grafanacassandradatasource_cassandra_1 ... done
khunter-rmbp15:GrafanaCassandraDatasource kirstenhunter$ docker-compose exec cassandra cqlsh -u cassandra -p cassandra -f ./test_data.cql
ERROR: No container found for cassandra_1

**Comment by HadesArchitect** [comment]
I can't reproduce it, neither another developer can. Looks like Cassandra failed to start at your side. Could you please provide `docker-compose logs cassandra`?

**Comment by synedra-datastax** [comment]
I think it should be looking for the longer container name (grafanacassandradatasource_cassandra_1)

khunter-rmbp15:GrafanaCassandraDatasource kirstenhunter$ docker compose up -d
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
[+] Running 2/2
 ⠿ grafanacassandradatasource_cassandra_1  Recreated                                                           0.2s
 ⠿ grafanacassandradatasource_grafana_1    Recreated                                                           0.6s
khunter-rmbp15:GrafanaCassandraDatasource kirstenhunter$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS         PORTS                                                       NAMES
9acb27afe799   grafana/grafana:7.3.6   "/run.sh"                9 seconds ago   Up 4 seconds   0.0.0.0:3000->3000/tcp                                      grafanacassandradatasource_grafana_1
6194579fb961   cassandra               "docker-entrypoint.s…"   9 seconds ago   Up 4 seconds   7000-7001/tcp, 7199/tcp, 9160/tcp, 0.0.0.0:9042->9042/tcp   grafanacassandradatasource_cassandra_1
0005d26d876c   kindest/node:v1.19.1    "/usr/local/bin/entr…"   13 days ago     Up 23 hours    127.0.0.1:45451->6443/tcp                                   kind-cassandra-control-plane
7e14e2c2b3b8   kindest/node:v1.19.1    "/usr/local/bin/entr…"   13 days ago     Up 23 hours                                                                kind-cassandra-worker
31b3ade1d3d1   kindest/node:v1.19.1    "/usr/local/bin/entr…"   13 days ago     Up 23 hours                                                                kind-cassandra-worker3
1e45e4acd0d4   kindest/node:v1.19.1    "/usr/local/bin/entr…"   13 days ago     Up 23 hours                                                                kind-cassandra-worker5
172b5c20e35b   kindest/node:v1.19.1    "/usr/local/bin/entr…"   13 days ago     Up 23 hours                                                                kind-cassandra-worker4
d9ead243211f   kindest/node:v1.19.1    "/usr/local/bin/entr…"   13 days ago     Up 23 hours                                                                kind-cassandra-worker2
khunter-rmbp15:GrafanaCassandraDatasource kirstenhunter$ docker-compose exec cassandra cqlsh -u cassandra -p cassandra -f ./test_data.cql 
ERROR: No container found for cassandra_1
khunter-rmbp15:GrafanaCassandraDatasource kirstenhunter$

**Comment by HadesArchitect** [comment]
First command you execute is `docker compose`, second is `docker-compose`. That's the issue.

**Comment by HadesArchitect** [comment]
Closing as inactive, feel free to reopen if the issue isnt solved
