### ISSUE TITLE
Support AWS Keyspaces

### ISSUE THREAD

**Issue by propalparolnapervom** [HadesArchitect/GrafanaCassandraDatasource#77]
Greetings.

As I can see, initially the plugin worked with Cassandra only. And the ability to work with AWS Keyspaces was added in [this](https://github.com/HadesArchitect/GrafanaCassandraDatasource/pull/65) PR.

Once appropriate PR was merged, I've built the code (with the necessary [Amazon certificate](https://www.amazontrust.com/repository/AmazonRootCA1.pem) included) by myself (as no official release with necessary commits created yet). 

The built plugin installed successfully. 

With help of `cqlsh` tool, I can successfully connect to AWS Keyspaces.
So I wouldn't expect any problems to do the same with help of the plugin if the same is in use:
- credentials;
- Amazon certificate;
- AWS Keyspace endpoint;
- server, from which you're trying to reach AWS Keyspaces.

Yet, a Datasource, that uses the plugin, can't connect to AWS Keyspaces.
No logs in Grafana.
And I can't find any ability to add DEBUG level to see, what's exactly wrong with my connection.

Does anyone already have a positive experience connecting this plugin to AWS Keyspaces?

Thank you.

**Comment by HadesArchitect** [comment]
Release that includes that code was done just a few minutes ago: https://github.com/HadesArchitect/GrafanaCassandraDatasource/releases/tag/0.4.0

**Comment by HadesArchitect** [comment]
Hey there, I have good news :) 

<img src="https://user-images.githubusercontent.com/1742301/107685833-c3c78000-6ca4-11eb-9899-c283a357bc8a.png" width="200" />

It works, I'll fix a minor issue and release a test version for you to try out.

**Comment by HadesArchitect** [comment]
Another news, as AWS Keyspaces is not a real Cassandra some CQL functions aren't supported:
```
cassandra-backend-datasource: Error while processing a query: IN is not yet supported
```
Issues like that cannot be solved at our side as it's due to Keyspaces limited capabilities. IN operator, UDFs etc. aren't supported ¯\_(ツ)_/¯

**Comment by HadesArchitect** [comment]
Released with #86

**Comment by HadesArchitect** [comment]
Docs are here, gonna expand them a bit later this week https://github.com/HadesArchitect/GrafanaCassandraDatasource/wiki/AWS-Keyspaces

**Comment by propalparolnapervom** [comment]
I just have checked version `0.5.0`: now it can reach AWS Keyspaces, indeed.

Thanks!

**Comment by propalparolnapervom** [comment]
P.S. Found interesting behavior of appropriate Data Source: once it was configured properly, any further changes are considered as correct configuration for the connection.

Thus, even an empty datasource is marked as a successful one after pushing `Save & Test` button:
![image](https://user-images.githubusercontent.com/37516081/109818466-ae0e0080-7c3b-11eb-8c50-41dc3a27f23c.png)


Not sure whether it's because of the plugin itself, tho.

**Comment by futuarmo** [comment]
> 
> 
> P.S. Found interesting behavior of appropriate Data Source: once it was configured properly, any further changes are considered as correct configuration for the connection.
> 
> Thus, even an empty datasource is marked as a successful one after pushing `Save & Test` button:
> ![image](https://user-images.githubusercontent.com/37516081/109818466-ae0e0080-7c3b-11eb-8c50-41dc3a27f23c.png)
> 
> Not sure whether it's because of the plugin itself, tho.

Thank you for info. It's known bug with several instances of data source and it will be fixed as soon as possible
