### ISSUE TITLE
Update plugin using Grafana Plugin SDK v7+

### ISSUE THREAD

**Issue by futuarmo** [HadesArchitect/GrafanaCassandraDatasource#89]
We should update our plugin from legacy implementation to new Grafana Plugin SDK 
https://grafana.com/tutorials/build-a-data-source-backend-plugin/

**Comment by HadesArchitect** [comment]
@futuarmo What's the time estimation on that? Should we include it in the 1.0.0 release?

**Comment by futuarmo** [comment]
@HadesArchitect it needs further investigation, in my opinion it's possible to migrate until 1.0. 
I propose don't connect release date to migration because I can't guarantee anything yet

**Comment by futuarmo** [comment]
Merged, will be released
